package Entities;
// Generated 19 mai 2016 09:30:32 by Hibernate Tools 4.3.1



/**
 * Administration generated by hbm2java
 */
public class Administration  implements java.io.Serializable {


     private int codeAdmin;
     private String password;

    public Administration() {
    }

    public Administration(int codeAdmin, String password) {
       this.codeAdmin = codeAdmin;
       this.password = password;
    }
   
    public int getCodeAdmin() {
        return this.codeAdmin;
    }
    
    public void setCodeAdmin(int codeAdmin) {
        this.codeAdmin = codeAdmin;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


