package Entities;
// Generated 19 mai 2016 09:30:32 by Hibernate Tools 4.3.1

import CoucheADO.MatiereADO;




/**
 * Compostage generated by hbm2java
 */
public class Compostage  implements java.io.Serializable {


     private Integer codeCompostage;
     private int numeroCompostage;
     private int codeNote;
     private float note;

    public Compostage() {
    }

    public Compostage(int numeroCompostage, int codeNote) {
       this.numeroCompostage = numeroCompostage;
       this.codeNote = codeNote;
       this.note = 0;
    }
   
    public Integer getCodeCompostage() {
        return this.codeCompostage;
    }
    
    public void setCodeCompostage(Integer codeCompostage) {
        this.codeCompostage = codeCompostage;
    }
    public int getNumeroCompostage() {
        return this.numeroCompostage;
    }
    
    public void setNumeroCompostage(int numeroCompostage) {
        this.numeroCompostage = numeroCompostage;
    }
    public int getCodeNote() {
        return this.codeNote;
    }
    
    public void setCodeNote(int codeNote) {
        this.codeNote = codeNote;
    }
    public float getNote() {
        return this.note;
    }
    
    public void setNote(float note) {
        this.note = note;
    }

   
}


