package Entities;
// Generated 19 mai 2016 09:30:32 by Hibernate Tools 4.3.1

import CoucheADO.EtudiantADO;




/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private int cin;
     private int numInscription;
     private String nom;
     private String prenom;
     private String adresse;
     private int tel;
     private int codeUser;
     private String password;
     private int groupe;

    public Etudiant() {
    }

    public Etudiant(int cin, int numInscription, String nom, String prenom, String adresse, int tel, int codeUser, String password, int groupe) {
       this.cin = cin;
       this.numInscription = numInscription;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.tel = tel;
       this.codeUser = codeUser;
       this.password = password;
       this.groupe = groupe;
    }
   
    public int getCin() {
        return this.cin;
    }
    
    public void setCin(int cin) {
        this.cin = cin;
    }
    public int getNumInscription() {
        return this.numInscription;
    }
    
    public void setNumInscription(int numInscription) {
        this.numInscription = numInscription;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public int getTel() {
        return this.tel;
    }
    
    public void setTel(int tel) {
        this.tel = tel;
    }
    public int getCodeUser() {
        return this.codeUser;
    }
    
    public void setCodeUser(int codeUser) {
        this.codeUser = codeUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(int groupe) {
        this.groupe = groupe;
    }
   
}


