package Entities;
// Generated 19 mai 2016 09:30:32 by Hibernate Tools 4.3.1

import CoucheADO.MatiereADO;
import CoucheADO.NiveauADO;
import java.util.ArrayList;
import java.util.List;




/**
 * Groupe generated by hbm2java
 */
public class Groupe  implements java.io.Serializable {


     private Integer codeGrp;
     private String nomGrp;
     private String abreviation;
     private int niveau;

    public Groupe() {
    }

    public Groupe(String nomGrp, String abreviation, int niveau) {
       this.nomGrp = nomGrp;
       this.abreviation = abreviation;
       this.niveau = niveau;
    }
   
    public Integer getCodeGrp() {
        return this.codeGrp;
    }
    
    public void setCodeGrp(Integer codeGrp) {
        this.codeGrp = codeGrp;
    }
    public String getNomGrp() {
        return this.nomGrp;
    }
    
    public void setNomGrp(String nomGrp) {
        this.nomGrp = nomGrp;
    }
    public String getAbreviation() {
        return this.abreviation;
    }
    
    public void setAbreviation(String abreviation) {
        this.abreviation = abreviation;
    }
    public int getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(int niveau) {
        this.niveau = niveau;
    }


    public String getNiveauName()
    {
        return NiveauADO.getNiveauById(this.niveau).getNomNiv();
    }
    public List<Matiere> getAllStudents(int ens, int groupe)
            {
                return MatiereADO.getMatieresByENSEIGNANT(ens, groupe);
            }
}


