package Entities;
// Generated 19 mai 2016 09:30:32 by Hibernate Tools 4.3.1

import CoucheADO.EnseignantADO;
import CoucheADO.GroupeADO;
import CoucheADO.MatiereADO;
import CoucheADO.NoteADO;




/**
 * Matiere generated by hbm2java
 */
public class Matiere  implements java.io.Serializable {


     private Integer codeMat;
     private String libelle;
     private float volumeC;
     private float volumeTd;
     private float volumeTp;
     private float coeffecient;
     private float credit;
     private int enseignant;
     private int groupe;

    public Matiere() {
    }

    public Matiere(String libelle, float volumeC, float volumeTd, float volumeTp, float coeffecient, float credit, int enseignant, int groupe) {
       this.libelle = libelle;
       this.volumeC = volumeC;
       this.volumeTd = volumeTd;
       this.volumeTp = volumeTp;
       this.coeffecient = coeffecient;
       this.credit = credit;
       this.enseignant = enseignant;
       this.groupe = groupe;
    }
   
    public Integer getCodeMat() {
        return this.codeMat;
    }
    
    public void setCodeMat(Integer codeMat) {
        this.codeMat = codeMat;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public float getVolumeC() {
        return this.volumeC;
    }
    
    public void setVolumeC(float volumeC) {
        this.volumeC = volumeC;
    }
    public float getVolumeTd() {
        return this.volumeTd;
    }
    
    public void setVolumeTd(float volumeTd) {
        this.volumeTd = volumeTd;
    }
    public float getVolumeTp() {
        return this.volumeTp;
    }
    
    public void setVolumeTp(float volumeTp) {
        this.volumeTp = volumeTp;
    }
    public float getCoeffecient() {
        return this.coeffecient;
    }
    
    public void setCoeffecient(float coeffecient) {
        this.coeffecient = coeffecient;
    }
    public float getCredit() {
        return this.credit;
    }
    
    public void setCredit(float credit) {
        this.credit = credit;
    }
    public int getEnseignant() {
        return this.enseignant;
    }
    
    public void setEnseignant(int enseignant) {
        this.enseignant = enseignant;
    }
    public int getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(int groupe) {
        this.groupe = groupe;
    }


public String getEnseignantName()
    {
         String nom=EnseignantADO.getEnseignantByCode(this.enseignant).getNom();
         String prenom=EnseignantADO.getEnseignantByCode(this.enseignant).getPrenom();

         return nom+" "+prenom;
    }
     public String getGroupeName()
    {       
         return GroupeADO.getGroupeById(this.groupe).getNomGrp();
    }
    public int CodeNiveau()
    {
        return GroupeADO.getGroupeById(this.groupe).getNiveau();
    }
      public long verifierCompostage()
    {
        return MatiereADO.VerifierCompostage(this.codeMat);
    }
      public int validite (int id)
      {
          return NoteADO.getAllNotesByMatiere(id).get(0).getValidite();
      }
      public Note note(int cin)
      {
          return NoteADO.getNoteByMatiere(cin,this.codeMat);
      }
}




