package Entities;
// Generated 19 mai 2016 12:25:46 by Hibernate Tools 4.3.1

import CoucheADO.EtudiantADO;
import CoucheADO.SessionADO;




/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private Integer code;
     private float noteTp;
     private float noteDs;
     private float noteExamen;
     private double notePresentielle;
     private int matiere;
     private int etudiant;
     private int session;
     private int validite;

    public Note() {
    }

    public Note(float noteTp, float noteDs, float noteExamen, double notePresentielle, int matiere, int etudiant, int session) {
       this.noteTp = noteTp;
       this.noteDs = noteDs;
       this.noteExamen = noteExamen;
       this.notePresentielle = notePresentielle;
       this.matiere = matiere;
       this.etudiant = etudiant;
       this.session = session;
       this.validite = 0;
    }
   
    public Integer getCode() {
        return this.code;
    }
    
    public void setCode(Integer code) {
        this.code = code;
    }
    public float getNoteTp() {
        return this.noteTp;
    }
    
    public void setNoteTp(float noteTp) {
        this.noteTp = noteTp;
    }
    public float getNoteDs() {
        return this.noteDs;
    }
    
    public void setNoteDs(float noteDs) {
        this.noteDs = noteDs;
    }
    public float getNoteExamen() {
        return this.noteExamen;
    }
    
    public void setNoteExamen(float noteExamen) {
        this.noteExamen = noteExamen;
    }
    public double getNotePresentielle() {
        return this.notePresentielle;
    }
    
    public void setNotePresentielle(double notePresentielle) {
        this.notePresentielle = notePresentielle;
    }
    public int getMatiere() {
        return this.matiere;
    }
    
    public void setMatiere(int matiere) {
        this.matiere = matiere;
    }
    public int getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(int etudiant) {
        this.etudiant = etudiant;
    }
    public int getSession() {
        return this.session;
    }
    
    public void setSession(int session) {
        this.session = session;
    }
    public int getValidite() {
        return this.validite;
    }
    
    public void setValidite(int validite) {
        this.validite = validite;
    }

 public String getSessionName ()
    {
        return SessionADO.getSessionByCode(this.session).getLibelle();
    }
    public String getEtudiantName ()
    {
        return EtudiantADO.getEtudiantByCode(this.etudiant).getNom()+" "+EtudiantADO.getEtudiantByCode(this.etudiant).getPrenom();
    }


}


